spring:
  application:
    name: sugarguard
  datasource:
    url: jdbc:h2:file:./data/sugarguard;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kakao:
  rest-api-key: ${KAKAO_API_KEY}

public-data:
  service-key: ${PUBLIC_API_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}