spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kakao:
  rest-api-key: ${KAKAO_API_KEY}

public-data:
  service-key: ${PUBLIC_API_KEY}

gemini:
  api-keys: ${GEMINI_API_KEY_1},${GEMINI_API_KEY_2}

ai:
  server-url: ${AI_SERVER_URL}